# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Topic', to='home.Topic')),
            ],
        ),
    ]
